services:
  nginx:
    build:
      context: nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - network

  app:
    build:
      context: app
    ports:
      - "8000:8000"
    volumes:
      - ./db/:/db
    depends_on:
      database:
        condition: service_healthy
        restart: true
    networks:
      - network

  database:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=twitter
    ports:
      - "5432:5432"
    volumes:
      - ./db/:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d twitter"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - network

networks:
  network:
    driver: bridge